"""Data models for Amazon affiliate automation."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Product:
    """Represents an Amazon product."""

    asin: str
    title: str
    price: Optional[str] = None
    currency: Optional[str] = None
    image_url: Optional[str] = None
    affiliate_link: Optional[str] = None
    rating: Optional[float] = None
    review_count: Optional[int] = None
    category: Optional[str] = None
    description: Optional[str] = None
    features: list[str] = field(default_factory=list)
    discount_percent: Optional[int] = None

    @classmethod
    def from_api_response(cls, data: dict) -> "Product":
        price_data = data.get("price", {})
        if isinstance(price_data, dict):
            current_price = price_data.get("current_price")
            currency = price_data.get("currency")
        else:
            current_price = str(price_data) if price_data else None
            currency = None

        return cls(
            asin=data.get("asin", ""),
            title=data.get("title", ""),
            price=current_price,
            currency=currency,
            image_url=data.get("image", data.get("thumbnail")),
            rating=data.get("rating"),
            review_count=data.get("reviews_count", data.get("review_count")),
            category=data.get("category"),
            description=data.get("description", ""),
            features=data.get("features", []),
            discount_percent=data.get("discount_percent", data.get("savings_percent")),
        )


@dataclass
class GeneratedContent:
    """Content generated by the AI agent for social media posting."""

    product: Product
    text: str
    hashtags: list[str] = field(default_factory=list)
    language: str = "en"

    @property
    def full_post(self) -> str:
        hashtag_str = " ".join(self.hashtags)
        return f"{self.text}\n\n{hashtag_str}".strip()


@dataclass
class ShortsScript:
    """YouTube Shorts script generated by AI."""

    product: Product
    hook: str  # First 3 seconds - attention grabber
    body: str  # Main content - product showcase
    cta: str  # Call to action
    title: str  # YouTube video title (SEO optimized)
    description: str  # YouTube video description with affiliate link
    tags: list[str] = field(default_factory=list)
    language: str = "en"
    duration_seconds: int = 30  # Target duration

    @property
    def full_script(self) -> str:
        return f"[HOOK - 0-3s]\n{self.hook}\n\n[BODY - 3-25s]\n{self.body}\n\n[CTA - 25-{self.duration_seconds}s]\n{self.cta}"

    @property
    def full_description(self) -> str:
        tag_str = " ".join(f"#{t.lstrip('#')}" for t in self.tags[:15])
        return f"{self.description}\n\n{tag_str}"


@dataclass
class PostResult:
    """Result of posting content to a platform."""

    platform: str
    success: bool
    post_id: Optional[str] = None
    url: Optional[str] = None
    error: Optional[str] = None
