"""Data models for Amazon affiliate automation."""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Product:
    """Represents an Amazon product."""

    asin: str
    title: str
    price: Optional[str] = None
    currency: Optional[str] = None
    image_url: Optional[str] = None
    affiliate_link: Optional[str] = None
    rating: Optional[float] = None
    category: Optional[str] = None

    @classmethod
    def from_api_response(cls, data: dict) -> "Product":
        return cls(
            asin=data.get("asin", ""),
            title=data.get("title", ""),
            price=data.get("price", {}).get("current_price"),
            currency=data.get("price", {}).get("currency"),
            image_url=data.get("image"),
            rating=data.get("rating"),
            category=data.get("category"),
        )


@dataclass
class GeneratedContent:
    """Content generated by the AI agent for posting."""

    product: Product
    text: str
    hashtags: list[str] = field(default_factory=list)
    language: str = "en"

    @property
    def full_post(self) -> str:
        hashtag_str = " ".join(self.hashtags)
        return f"{self.text}\n\n{hashtag_str}".strip()


@dataclass
class PostResult:
    """Result of posting content to a platform."""

    platform: str
    success: bool
    post_id: Optional[str] = None
    error: Optional[str] = None
